### PR TITLE
Added the Linux File Structure information

### PR DESCRIPTION
**Pull request by AniketNS**
Hey maintainers,

After watching Siddhant's YouTube video, I came here and want to contribute to this project and gain knowledge. I've added the file about  Linux file structure information as my understanding after watching his video about Linux File structure. 

Please tell me if there I can change in this.

### CODE REVIEW

**Comment by afro-coder** [comment]
Hey @AniketNS thank you for contributing I'll take a look into this.

Can you also maybe add sources as to where you're gathering data from?

**Comment by AniketNS** [comment]
Hey @afro-coder, I gathered all the written information from Siddhant kishty's video on Linux File Management. And also took help from ChatGPT for the clarification while writing what I learned from his video.

**Comment by afro-coder** [comment]
Ah, cool will need to do another review then.

**Comment by AniketNS** [comment]
> Ah, cool will need to do another review then.

Sure and also tell me if there is something I should add more.

**Pull request merged**
